// Sign In
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_LOADING = "SIGN_IN_LOADING";
export const SIGN_IN_FAILING = "SIGN_IN_FAILING";

// Sign Up
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_LOADING = "SIGN_UP_LOADING";
export const SIGN_UP_FAILING = "SIGN_UP_FAILING";

// Log Out
export const LOG_OUT = "LOG_OUT";

// Edit Profile
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_LOADING = "EDIT_PROFILE_LOADING";
export const EDIT_PROFILE_FAILING = "EDIT_PROFILE_FAILING";

// Load Categories
export const LOAD_CATEGORIES_SUCCESS = "LOAD_CATEGORIES_SUCCESS";
export const LOAD_CATEGORIES_LOADING = "LOAD_CATEGORIES_LOADING";
export const LOAD_CATEGORIES_FAILING = "LOAD_CATEGORIES_FAILING";

// Find Category
export const FIND_CATEGORY = "FIND_CATEGORY";

// Load Quizzes
export const LOAD_QUIZZES_SUCCESS = "LOAD_QUIZZES_SUCCESS";
export const LOAD_QUIZZES_LOADING = "LOAD_QUIZZES_LOADING";
export const LOAD_QUIZZES_FAILING = "LOAD_QUIZZES_FAILING";

export const SUCCESS = "SUCCESS";
export const LOADING = "LOADING";
export const FAILING = "FAILING";