<<<<<<< HEAD
// Default types
=======
// Sign In
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_LOADING = "SIGN_IN_LOADING";
export const SIGN_IN_FAILING = "SIGN_IN_FAILING";

// Sign Up
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_LOADING = "SIGN_UP_LOADING";
export const SIGN_UP_FAILING = "SIGN_UP_FAILING";

// Log In
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_LOADING = "LOG_IN_LOADING";
export const LOG_IN_FAILING = "LOG_IN_FAILING";

// Log Out
export const LOG_OUT = "LOG_OUT";

// Edit Profile
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_LOADING = "EDIT_PROFILE_LOADING";
export const EDIT_PROFILE_FAILING = "EDIT_PROFILE_FAILING";

// Load Categories
export const LOAD_CATEGORIES_SUCCESS = "LOAD_CATEGORIES_SUCCESS";
export const LOAD_CATEGORIES_LOADING = "LOAD_CATEGORIES_LOADING";
export const LOAD_CATEGORIES_FAILING = "LOAD_CATEGORIES_FAILING";

// Find Category
export const FIND_CATEGORY = "FIND_CATEGORY";

// Load Quizzes
export const LOAD_QUIZZES_SUCCESS = "LOAD_QUIZZES_SUCCESS";
export const LOAD_QUIZZES_LOADING = "LOAD_QUIZZES_LOADING";
export const LOAD_QUIZZES_FAILING = "LOAD_QUIZZES_FAILING";

// Find Quiz
export const FIND_QUIZ = "FIND_QUIZ";

// Load Quiz
export const LOAD_QUIZ_SUCCESS = "LOAD_QUIZ_SUCCESS";
export const LOAD_QUIZ_LOADING = "LOAD_QUIZ_LOADING";
export const LOAD_QUIZ_FAILING = "LOAD_QUIZ_FAILING";

// Set selected answers
export const SET_SELECTED_ANSWERS = "SET_SELECTED_ANSWERS";

// Buttons state
export const DISABLE_GAME_BUTTONS = "DISABLE_GAME_BUTTONS";
export const ENABLE_GAME_BUTTONS = "ENABLE_GAME_BUTTONS";

// Next question
export const NEXT_QUESTION = "NEXT_QUESTION";

// Right answer
export const RIGHT_ANSWER = "RIGHT_ANSWER";

// Set background color
export const SET_BACKGROUND_COLOR = "SET_BACKGROUND_COLOR";

// Update score
export const UPDATE_SCORE = "UPDATE_SCORE";

// Load rating
export const LOAD_RATING_SUCCESS = "LOAD_RATING_SUCCESS";
export const LOAD_RATING_LOADING = "LOAD_RATING_LOADING";
export const LOAD_RATING_FAILING = "LOAD_RATING_FAILING";

// Load user profile
export const LOAD_USER_PROFILE_SUCCESS = "LOAD_USER_PROFILE_SUCCESS";
export const LOAD_USER_PROFILE_LOADING = "LOAD_USER_PROFILE_LOADING";
export const LOAD_USER_PROFILE_FAILING = "LOAD_USER_PROFILE_FAILING";

// Load my quizzes
export const LOAD_MY_QUIZZES_SUCCESS = "LOAD_MY_QUIZZES_SUCCESS";
export const LOAD_MY_QUIZZES_LOADING = "LOAD_MY_QUIZZES_LOADING";
export const LOAD_MY_QUIZZES_FAILING = "LOAD_MY_QUIZZES_FAILING";

// Load my quiz
export const LOAD_MY_QUIZ_SUCCESS = "LOAD_MY_QUIZ_SUCCESS";
export const LOAD_MY_QUIZ_LOADING = "LOAD_MY_QUIZ_LOADING";
export const LOAD_MY_QUIZ_FAILING = "LOAD_MY_QUIZ_FAILING";

// Create quiz
export const CREATE_QUIZ_SUCCESS = "CREATE_QUIZ_SUCCESS";
export const CREATE_QUIZ_LOADING = "CREATE_QUIZ_LOADING";
export const CREATE_QUIZ_FAILING = "CREATE_QUIZ_FAILING";

// Delete quiz
export const DELETE_QUIZ_SUCCESS = "DELETE_QUIZ_SUCCESS";
export const DELETE_QUIZ_LOADING = "DELETE_QUIZ_LOADING";
export const DELETE_QUIZ_FAILING = "DELETE_QUIZ_FAILING";

>>>>>>> dev
export const SUCCESS = "SUCCESS";
export const LOADING = "LOADING";
export const FAILING = "FAILING";